### ISSUE TITLE
AttributeError: 'CityJsonLoaderDialog' object has no attribute 'metadataPlainTextEdit' 

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/cityjson-qgis-plugin#18]
Just came across this today with version 0.4.0:
```
Traceback (most recent call last):
  File "/home/balazs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/gui/cityjson_loader.py", line 91, in select_cityjson_file
    self.clear_file_information()
  File "/home/balazs/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/gui/cityjson_loader.py", line 123, in clear_file_information
    self.dlg.metadataPlainTextEdit.setPlainText("")
AttributeError: 'CityJsonLoaderDialog' object has no attribute 'metadataPlainTextEdit'
```

Python version: 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
QGIS version: 3.8.2-Zanzibar Zanzibar, e0a5e94093 

Let me know if you need the data that I tried to load.

**Comment by liberostelios** [comment]
Thanks for submitting!

Fixed in 9b7b3d943d2c359caec2ae9184a817cf14668ef2
