### ISSUE TITLE
Crash on loading in QGIS 3.10.0 on Linux

### ISSUE THREAD

**Issue by tomvantilburg** [tudelft3d/cityjson-qgis-plugin#25]
Couldn't load plugin 'CityJSON-loader' due to an error when calling its classFactory() method 

ValueError: could not convert string to float: '6378137.0.' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/__init__.py", line 35, in classFactory
    from .gui.cityjson_loader import CityJsonLoader
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/gui/cityjson_loader.py", line 39, in 
    from ..cjio import cityjson
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python/plugins/CityJSON-loader/cjio/cityjson.py", line 15, in 
    import pyproj
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/__init__.py", line 81, in 
    from pyproj.crs import CRS  # noqa: F401
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/crs.py", line 57, in 
    from pyproj.geod import Geod
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/local/lib/python3.7/dist-packages/pyproj/geod.py", line 42, in 
    pj_ellps = get_ellps_map()
  File "pyproj/_list.pyx", line 39, in pyproj._list.get_ellps_map
ValueError: could not convert string to float: '6378137.0.'

Python version: 3.7.5rc1 (default, Oct  8 2019, 16:47:45) [GCC 9.2.1 20191008] 
QGIS version: 3.10.0-A Coruña A Coruña, 6c816b4204 

Python Path:
/usr/share/qgis/python
/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python
/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/dist-packages
/usr/local/lib/python3.7/dist-packages/cjio-0.6-py3.7.egg
/usr/lib/python3/dist-packages
/home/tomt/.local/share/QGIS/QGIS3/profiles/default/python
/usr/lib/python3/dist-packages/IPython/extensions
.

**Comment by liberostelios** [comment]
That seems to be an issue with Ubuntu 19.10 specifically. I'll take a look at it. Thanks a lot for reporting!

**Comment by liberostelios** [comment]
Okay, I found a nice fix, @tomvantilburg! Use [Arch Linux](https://www.archlinux.org/)...

**Comment by tomvantilburg** [comment]
I suggest adding this recommendation to the documentation.

**Comment by liberostelios** [comment]
Is QGIS part of the Ubuntu 19.10 repositories or installed through ppa?

**Comment by liberostelios** [comment]
The issue turned out o be something related to the specific installation.
